-- Generated by tools/generate_data.py. Do not edit by hand.
LFRaiderData = {
    generatedAt = "2026-08-08T18:21:57.675411+00:00",
    source = "warcraftlogs-scrape",
    scoreScale = 10,
    totalCharacters = 0,
    realms = {
    },
    realmNames = {
    },
}
