-- Generated by tools/generate_data.py. Do not edit by hand.
LFRaiderData = {
    generatedAt = "2026-04-10T12:35:45Z",
    source = "warcraftlogs-api-v2",
    scoreScale = 10,
    itemScoreScale = 1,
    totalCharacters = 0,
    fields = {
        wclOverall = 1,
        itemScore = 2,
    },
    realms = {
    },
    realmNames = {
    },
}
