-- Generated by tools/generate_data.py. Do not edit by hand.
LFRaiderData = {
    generatedAt = "2026-04-10T00:00:00Z",
    source = "manual-seed",
    scoreScale = 10,
    itemScoreScale = 1,
    totalCharacters = 1,
    fields = {
        wclOverall = 1,
        itemScore = 2,
    },
    realms = {
        ["dreamscythe"] = {
            ["vocoder"] = {747, 126},
        },
    },
    realmNames = {
        ["dreamscythe"] = "Dreamscythe",
    },
}
