#!/usr/bin/env python3
"""Generate the runtime Lua score table from a JSON score document."""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


DEFAULT_SCALE = 10


def normalize_name(value: str) -> str:
    value = value.strip()
    if not value:
        raise ValueError("character name cannot be empty")
    return value.lower()


def normalize_realm(value: str) -> str:
    value = value.strip()
    if not value:
        raise ValueError("realm cannot be empty")
    return re.sub(r"[\s\-']", "", value).lower()


def lua_string(value: str) -> str:
    escaped = []
    for char in value:
        codepoint = ord(char)
        if char == "\\":
            escaped.append("\\\\")
        elif char == '"':
            escaped.append('\\"')
        elif char == "\n":
            escaped.append("\\n")
        elif char == "\r":
            escaped.append("\\r")
        elif char == "\t":
            escaped.append("\\t")
        elif codepoint < 32:
            escaped.append(f"\\{codepoint:03d}")
        else:
            escaped.append(char)

    return '"' + "".join(escaped) + '"'


def load_characters(document: dict[str, Any]) -> list[dict[str, Any]]:
    if isinstance(document.get("characters"), list):
        return document["characters"]

    if isinstance(document.get("realms"), dict):
        characters: list[dict[str, Any]] = []
        for realm, scores in document["realms"].items():
            if not isinstance(scores, dict):
                continue
            for name, score in scores.items():
                characters.append({"name": name, "realm": realm, "score": score})
        return characters

    raise ValueError("input JSON must contain either characters[] or realms{}")


def build_payload(document: dict[str, Any]) -> dict[str, Any]:
    scale = int(document.get("scoreScale") or DEFAULT_SCALE)
    if scale <= 0:
        raise ValueError("scoreScale must be greater than zero")

    realms: dict[str, dict[str, int]] = {}
    realm_names: dict[str, str] = {}

    for character in load_characters(document):
        name = str(character.get("name") or "").strip()
        realm = str(character.get("realm") or "").strip()
        if not name or not realm:
            raise ValueError(f"character entry is missing name or realm: {character!r}")

        score_value = character.get("wclOverall", character.get("wclScore", character.get("ranking", character.get("score"))))
        if score_value is None:
            continue

        score = float(score_value)
        if score < 0 or score > 100:
            raise ValueError(f"WCL score for {name}-{realm} must be between 0 and 100")

        name_key = normalize_name(name)
        realm_key = normalize_realm(realm)
        realms.setdefault(realm_key, {})[name_key] = int(round(score * scale))
        realm_names.setdefault(realm_key, realm)

    return {
        "generatedAt": document.get("generatedAt")
        or datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "source": document.get("source") or "unknown",
        "scoreScale": scale,
        "totalCharacters": sum(len(scores) for scores in realms.values()),
        "realms": realms,
        "realmNames": realm_names,
    }


def render_lua(payload: dict[str, Any]) -> str:
    lines = [
        "-- Generated by tools/generate_data.py. Do not edit by hand.",
        "LFRaiderData = {",
        f"    generatedAt = {lua_string(str(payload['generatedAt']))},",
        f"    source = {lua_string(str(payload['source']))},",
        f"    scoreScale = {int(payload['scoreScale'])},",
        f"    totalCharacters = {int(payload['totalCharacters'])},",
        "    realms = {",
    ]

    for realm_key in sorted(payload["realms"]):
        lines.append(f"        [{lua_string(realm_key)}] = {{")
        for name_key in sorted(payload["realms"][realm_key]):
            lines.append(f"            [{lua_string(name_key)}] = {int(payload['realms'][realm_key][name_key])},")
        lines.append("        },")

    lines.extend([
        "    },",
        "    realmNames = {",
    ])

    for realm_key in sorted(payload["realmNames"]):
        lines.append(f"        [{lua_string(realm_key)}] = {lua_string(payload['realmNames'][realm_key])},")

    lines.extend([
        "    },",
        "}",
        "",
    ])

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path, help="Source JSON score document")
    parser.add_argument("output", type=Path, help="Runtime Lua file to write")
    args = parser.parse_args()

    document = json.loads(args.input.read_text(encoding="utf-8"))
    payload = build_payload(document)
    args.output.write_text(render_lua(payload), encoding="utf-8", newline="\n")
    print(f"wrote {args.output} with {payload['totalCharacters']} characters")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
